import numpy as np
from scipy.stats import beta
from sklearn.base import clone

from .basic import FeatureTweakingExplainer
from .utils import Y_TARGET, parse_trees



class BetaRobustExplainer(FeatureTweakingExplainer):
    def __init__(
        self, 
        estimator: any, 
        constraints: dict,
        cost_type: str = 'tlps',
        cost_ord: int = 1,
        max_features: int = -1,
        plausibility: float = 1.0,
        prune_level: float = 1.0,
        merge_level: int = 2,
        max_search: float = 1.0,
        temperature: float = 0.0,
        tolerance: float = 0.05,
        n_sampling: int = 30,
        alpha: float = 0.95,
        delta: float | list = 0.8,
    ):
        
        super().__init__(
            estimator, 
            constraints, 
            cost_type, 
            cost_ord, 
            max_features, 
            plausibility,
            prune_level,
            merge_level, 
            max_search, 
            temperature, 
            tolerance
        )   
        self.n_sampling = n_sampling
        self.alpha = alpha
        self.delta = delta


    def initialize(self, X, y):
        
        self = super().initialize(X)
        
        admissible_estimators = []
        n_estimators = self.estimator.n_estimators
        max_depth = self.estimator.max_depth
        for _ in range(self.n_sampling):
            estimator = clone(self.estimator)
            estimator.n_estimators = np.random.randint(max(1, int(0.8 * n_estimators)), int(1.2 * n_estimators))
            estimator.max_depth = np.random.randint(max(1, int(0.8 * max_depth)), int(1.2 * max_depth))
            estimator = estimator.fit(X, y)
            admissible_estimators.append(estimator)
        self.admissible_estimators_ = admissible_estimators
        
        return self


    def _get_validity(self, X, A):
        
        # Compute predictions for all counterfactual instances generated by applying actions
        X_cf = np.repeat(X, A.shape[1], axis=0) + np.concatenate(A, axis=0)
        if self.ensemble_type_ == 'boosting':
            y_pred = self.estimator.predict(X_cf)
        else:
            y_prob = np.array([tree.predict(X_cf) for tree in self.trees_]).T.mean(axis=1)
            y_pred = (y_prob >= 0.5).astype(int)
        
        # Check validity of actions based on whether the predicted class is the target class
        is_valid = (y_pred == Y_TARGET).reshape(A.shape[0], A.shape[1]).astype(np.bool_)        

        y_ones = np.full(X_cf.shape[0], fill_value=0.5)
        y_zeros = np.full(X_cf.shape[0], fill_value=0.5)
        for estimator in self.admissible_estimators_:
            if self.ensemble_type_ == 'boosting':
                y_pred = (estimator.predict(X_cf) == Y_TARGET).astype(float)
            else:
                y_prob = np.array([tree.predict(X_cf) for tree in parse_trees(estimator)]).T.mean(axis=1)
                y_pred = (y_prob > 0.5).astype(float) if Y_TARGET == 1 else (y_prob <= 0.5).astype(float)
            y_ones += y_pred
            y_zeros += 1 - y_pred
        left_bounds = beta.ppf(1 - self.alpha, y_ones, y_zeros)

        if isinstance(self.delta, float):
            delta = np.array([self.delta])
        else:
            delta = np.array(self.delta)
        is_valid_beta = np.zeros((delta.shape[0], A.shape[0], A.shape[1]), dtype=np.bool_)
        for i in range(delta.shape[0]):
            is_valid_beta[i] = (left_bounds >= delta[i]).reshape(A.shape[0], A.shape[1])
        is_valid = is_valid * is_valid_beta

        return is_valid
